<?php
require_once __DIR__.'/../../config/db.php';
class W2Model{
 private $db;private const FIELDS=['manager_name','recruiter_name','project_consultant_name','project_start_date','project_end_date','position_title','work_address','consultant_name','consultant_address','consultant_phone','consultant_email','emergency_contact','emergency_address','employment_w2','employment_1099','employment_corp_to_corp','end_client_name','end_client_address','reporting_manager','client_phone','client_fax','client_email','switchboard_extension','client_website','project_name','team_name','invoice_company_name','invoice_address','invoice_phone','invoice_fax','invoice_email','timesheet_email','invoice_website','invoice_contact_person','net_payment_terms','invoice_terms','comments','h1b_validity','lca_h1b_amendment'];
 function __construct(){global $conn;$this->db=$conn;}private function values($d){$v=[];foreach(self::FIELDS as $f)$v[$f]=$d[$f]??'';foreach(['employment_w2','employment_1099','employment_corp_to_corp']as$f)$v[$f]=!empty($d[$f])?1:0;return$v;}
 function create($d){$v=$this->values($d);$cols=implode(',',self::FIELDS);$marks=implode(',',array_fill(0,count(self::FIELDS),'?'));$s=$this->db->prepare("INSERT INTO w2_forms ($cols) VALUES ($marks)");$types=str_repeat('s',count(self::FIELDS));$args=array_values($v);$s->bind_param($types,...$args);if(!$s->execute())throw new Exception($s->error);return$this->get($this->db->insert_id);}
 function get($id){$s=$this->db->prepare('SELECT * FROM w2_forms WHERE id=?');$s->bind_param('i',$id);$s->execute();return$s->get_result()->fetch_assoc();}
 function list($page,$limit,$search){$offset=($page-1)*$limit;$q='%'.$search.'%';$where='WHERE consultant_name LIKE ? OR manager_name LIKE ? OR end_client_name LIKE ? OR invoice_company_name LIKE ?';$c=$this->db->prepare("SELECT COUNT(*) total FROM w2_forms $where");$c->bind_param('ssss',$q,$q,$q,$q);$c->execute();$total=(int)$c->get_result()->fetch_assoc()['total'];$s=$this->db->prepare("SELECT id,consultant_name,manager_name,end_client_name,project_name,created_at,updated_at FROM w2_forms $where ORDER BY created_at DESC LIMIT ? OFFSET ?");$s->bind_param('ssssii',$q,$q,$q,$q,$limit,$offset);$s->execute();return['data'=>$s->get_result()->fetch_all(MYSQLI_ASSOC),'total'=>$total,'page'=>$page,'limit'=>$limit];}
 function update($id,$d){$v=$this->values($d);$set=implode('=?,',self::FIELDS).'=?';$s=$this->db->prepare("UPDATE w2_forms SET $set WHERE id=?");$types=str_repeat('s',count(self::FIELDS)).'i';$args=array_values($v);$args[]=$id;$s->bind_param($types,...$args);if(!$s->execute())throw new Exception($s->error);return$this->get($id);}
 function delete($id){$s=$this->db->prepare('DELETE FROM w2_forms WHERE id=?');$s->bind_param('i',$id);$s->execute();return$s->affected_rows>0;}
}
