CREATE TABLE IF NOT EXISTS user_smtp_credentials (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 user_id INT UNSIGNED NOT NULL,
 smtp_host VARCHAR(190) NOT NULL,
 smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587,
 encryption ENUM('tls','ssl','none') NOT NULL DEFAULT 'tls',
 smtp_username VARCHAR(190) NOT NULL,
 encrypted_password TEXT NOT NULL,
 from_name VARCHAR(150) NOT NULL DEFAULT 'BeeData Technologies',
 verified_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uq_user_smtp(user_id),
 CONSTRAINT fk_user_smtp_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;