<?php
class AttendancePolicyService {
 public function calculate(int $employeeId,string $month):array {
  global $conn;if(!preg_match('/^\d{4}-\d{2}$/',$month))throw new InvalidArgumentException('Invalid attendance month.');
  $start=new DateTimeImmutable($month.'-01');$end=$start->modify('last day of this month');$a1=$start->format('Y-m-d');$a2=$end->format('Y-m-d');
  $s=$conn->prepare('SELECT date_of_joining,created_on FROM employees WHERE id=?');$s->bind_param('i',$employeeId);$s->execute();$employee=$s->get_result()->fetch_assoc();if(!$employee)throw new RuntimeException('Employee not found.');$joining=$employee['date_of_joining']?:substr((string)$employee['created_on'],0,10);$joiningDate=$joining?new DateTimeImmutable($joining):null;
  $weekends=0;for($d=$start;$d<=$end;$d=$d->modify('+1 day'))if((int)$d->format('N')>=6)$weekends++;
  $h=$conn->prepare('SELECT holiday_date FROM holidays WHERE holiday_date BETWEEN ? AND ? AND DAYOFWEEK(holiday_date) NOT IN(1,7)');$h->bind_param('ss',$a1,$a2);$h->execute();$holidaySet=[];$hr=$h->get_result();while($holiday=$hr->fetch_assoc())$holidaySet[$holiday['holiday_date']]=true;$holidays=(float)count($holidaySet);$working=max(0,(int)$end->format('t')-$weekends-$holidays);
  $a=$conn->prepare("SELECT COUNT(DISTINCT date) present_days,SUM(work_status='half_day') half_days FROM attendance WHERE employee_id=? AND date BETWEEN ? AND ?");$a->bind_param('iss',$employeeId,$a1,$a2);$a->execute();$att=$a->get_result()->fetch_assoc();$present=(float)($att['present_days']??0);$halfs=(float)($att['half_days']??0);$worked=max(0,$present-($halfs*.5));
  $l=$conn->prepare("SELECT leave_type,start_date,end_date,duration FROM leave_requests WHERE employee_id=? AND status='approved' AND start_date<=? AND end_date>=?");$l->bind_param('iss',$employeeId,$a2,$a1);$l->execute();$requestedCl=0.0;$pl=0.0;$upl=0.0;$rows=$l->get_result();while($row=$rows->fetch_assoc()){$from=max($start,new DateTimeImmutable($row['start_date']));$to=min($end,new DateTimeImmutable($row['end_date']));$days=0.0;for($day=$from;$day<=$to;$day=$day->modify('+1 day')){if((int)$day->format('N')>=6||isset($holidaySet[$day->format('Y-m-d')]))continue;$days+=$row['duration']==='full_day'?1.0:.5;}if($row['leave_type']==='casual')$requestedCl+=$days;elseif(in_array($row['leave_type'],['paid','sick'],true))$pl+=$days;elseif(in_array($row['leave_type'],['unpaid','bereavement','other'],true))$upl+=$days;}
  $eligible=$joiningDate&&$end >= $joiningDate->modify('+3 months');$entitlement=$eligible?1.0:0.0;$cl=min($requestedCl,$entitlement);$upl+=max(0,$requestedCl-$cl);$payable=max(0,$working-$upl);
  $result=['calendar_days'=>(int)$end->format('t'),'weekend_days'=>$weekends,'days_off'=>$weekends,'holiday_days'=>$holidays,'working_days'=>$working,'max_payable_days'=>$working,'present_days'=>$present,'half_days'=>$halfs,'worked_days'=>$worked,'pl_days'=>$pl,'cl_days'=>$cl,'casual_leave_requested'=>$requestedCl,'casual_leave_entitlement'=>$entitlement,'upl_days'=>$upl,'payable_days'=>$payable,'net_paid_days'=>$payable,'leave_eligible'=>$eligible,'joining_date'=>$joining];
  $o=$conn->prepare('SELECT overrides_json FROM attendance_monthly_adjustments WHERE employee_id=? AND attendance_month=?');$o->bind_param('is',$employeeId,$month);$o->execute();$row=$o->get_result()->fetch_assoc();$overrides=$row?(json_decode($row['overrides_json'],true)?:[]):[];foreach($overrides as $key=>$value)if(array_key_exists($key,$result)&&is_numeric($value))$result[$key]=(float)$value;$result['overrides']=$overrides;return $result;
 }
 public function save(int $employeeId,string $month,array $input,int $userId):array {global $conn;$allowed=['holiday_days','working_days','present_days','half_days','worked_days','pl_days','cl_days','upl_days','payable_days','net_paid_days'];$values=[];foreach($allowed as $key)if(array_key_exists($key,$input)&&$input[$key]!==''&&is_numeric($input[$key]))$values[$key]=max(0,(float)$input[$key]);$json=json_encode($values);$s=$conn->prepare("INSERT INTO attendance_monthly_adjustments(employee_id,attendance_month,overrides_json,updated_by) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE overrides_json=VALUES(overrides_json),updated_by=VALUES(updated_by)");$s->bind_param('issi',$employeeId,$month,$json,$userId);$s->execute();return $this->calculate($employeeId,$month);}
}