<?php
function employeePreOfferRoles(): array {
    return [
        'sr_bench_sales'=>['name'=>'Sr. Bench Sales','responsibilities'=>['Manage consultant marketing, submissions and placement pipelines.','Build and maintain relationships with vendors, recruiters and clients.','Negotiate rates, coordinate interviews and mentor junior bench sales team members.','Maintain accurate CRM records, follow-ups and performance reports.']],
        'jr_bench_sales'=>['name'=>'Jr. Bench Sales','responsibilities'=>['Support consultant marketing and identify suitable contract opportunities.','Contact vendors and recruiters and submit accurate candidate profiles.','Coordinate interviews and follow up on submissions under senior guidance.','Keep availability, submission and communication records up to date.']],
        'sr_it_recruiter'=>['name'=>'Sr. IT Recruiter','responsibilities'=>['Lead end-to-end technical sourcing, screening and recruitment.','Understand client requirements and evaluate candidate technical fit.','Coordinate interviews, offers and hiring follow-ups with stakeholders.','Mentor junior recruiters and maintain recruiting quality and accurate pipeline reports.']],
        'jr_it_recruiter'=>['name'=>'Jr. IT Recruiter','responsibilities'=>['Source candidates through job portals, professional networks and referrals.','Screen resumes and conduct initial candidate conversations.','Schedule interviews and maintain timely candidate follow-ups.','Maintain accurate recruiting records and learn technical screening under senior guidance.']],
        'hr'=>['name'=>'HR','responsibilities'=>['Coordinate employee onboarding, documentation and personnel records.','Support attendance, leave, payroll inputs and employee queries.','Communicate company policies and help maintain a professional workplace.','Handle confidential employee information responsibly and coordinate with management.']],
        'web_developer'=>['name'=>'Web Developer','responsibilities'=>['Develop and maintain responsive web applications and interfaces.','Integrate APIs and collaborate on database-backed application features.','Test, debug and improve application performance, accessibility and security.','Collaborate with the team through code reviews, documentation and delivery planning.']]
    ];
}
function employeePreOfferContent(string $roleKey,string $candidateName,string $url): array {
    $roles=employeePreOfferRoles();
    if (!isset($roles[$roleKey])) throw new InvalidArgumentException('Please select a valid role before sending the pre-offer invitation.');
    $role=$roles[$roleKey];$escape=fn($value)=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');
    $name=$candidateName!==''?$candidateName:'Candidate';$items='';
    foreach ($role['responsibilities'] as $responsibility) $items.='<li style="margin:0 0 10px">'.$escape($responsibility).'</li>';
    $html='<!doctype html><html><body style="margin:0;background:#f2f5fa;font-family:Arial,sans-serif;color:#243247"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:30px 12px"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="width:100%;max-width:640px;margin:auto;background:#fff;border-radius:16px;overflow:hidden"><tr><td style="background:#172554;padding:30px;color:#fff"><img src="cid:brand-logo" width="180" alt="BeeData Technologies" style="background:#fff;padding:10px;border-radius:8px;max-width:80%"><p style="font-size:12px;letter-spacing:2px;margin:22px 0 10px;color:#c7d2fe">BEEDATA TECHNOLOGIES · PRE-OFFER INVITATION</p><h1 style="margin:0;font-size:30px;line-height:1.25">Congratulations on your selection!</h1></td></tr><tr><td style="padding:30px;line-height:1.7;font-size:15px"><p>Dear '.$escape($name).',</p><p>We are pleased to inform you that you have been selected for the role of <strong>'.$escape($role['name']).'</strong> at <strong>BeeData Technologies</strong>. We look forward to welcoming you to our team.</p><div style="padding:18px;background:#eef2ff;border-left:4px solid #4f46e5;border-radius:8px"><span style="font-size:12px;color:#64748b">SELECTED ROLE</span><h2 style="font-size:22px;margin:5px 0;color:#3730a3">'.$escape($role['name']).'</h2><p style="margin:0;font-size:13px">Work location: Visakhapatnam</p></div><h2 style="font-size:18px;margin-top:28px">Your role & responsibilities</h2><ul style="padding-left:20px;font-size:14px">'.$items.'</ul><h2 style="font-size:18px;margin-top:28px">Next step: complete your information form</h2><p>Please provide your family details, previous work experience (if applicable), education, certifications and references, and attach the relevant documents.</p><p style="text-align:center;margin:28px 0"><a href="'.$escape($url).'" style="display:inline-block;background:#3730a3;color:#fff;text-decoration:none;padding:15px 24px;border-radius:9px;font-weight:bold">Complete My Information Form</a></p><p style="font-size:12px;color:#64748b">Your private link expires in 7 days and can be submitted once. Keep it confidential.</p><p>Our HR team will share your formal offer and joining details after reviewing your information. Please contact your HR coordinator if you need assistance.</p><p>Warm regards,<br><strong>HR Team</strong><br>BeeData Technologies</p><p style="font-size:11px;color:#64748b;overflow-wrap:anywhere">If the button does not open, use this link:<br><a href="'.$escape($url).'">'.$escape($url).'</a></p></td></tr><tr><td style="padding:18px 30px;background:#f8fafc;color:#64748b;font-size:12px">BeeData Technologies · Building careers, connecting opportunities.</td></tr></table></td></tr></table></body></html>';
    $plain='Dear '.$name.",\n\nCongratulations! You have been selected as ".$role['name']." at BeeData Technologies.\n\nRole & responsibilities:\n- ".implode("\n- ",$role['responsibilities'])."\n\nComplete your information form: ".$url."\nThe link expires in 7 days and can be submitted once.\n\nOur HR team will share your formal offer and joining details after reviewing your information.\n\nWarm regards,\nHR Team\nBeeData Technologies";
    return ['subject'=>'Congratulations! Your '.$role['name'].' selection | BeeData Technologies','html'=>$html,'plain'=>$plain];
}
